### PR TITLE
pin pandas<2.1

### PR DESCRIPTION
**Pull request by CagtayFabry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by CagtayFabry** [comment]
@conda-forge-admin, please rerender

**Comment by marscher** [comment]
Does this mean, that the PyPI package is currently broken too?

**Comment by CagtayFabry** [comment]
Since we can't update dependencies there, it will probably install pandas 2.1 and break

so yes, unfortunately

**Comment by CagtayFabry** [comment]
I think this can be changed again to `pandas<2.2`, correct @marscher ?

**Comment by marscher** [comment]
I think you're right @CagtayFabry, because 2.3 will probably fail for the old unit suffixes.

**Comment by marscher** [comment]
But I'd favor a new release anyways.

**Comment by CagtayFabry** [comment]
Yes this is quite breaking. I can release a new version next week

**Pull request merged**
