### PR TITLE
Scipy versions

### PR DESCRIPTION
**Pull request by marscher**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

fyi @CagtayFabry, @vhirtham

### CODE REVIEW

**Comment by marscher** [comment]
@conda-forge-admin please rerender

**Comment by CagtayFabry** [comment]
thanks @marscher 

scipy 1.6.2 is not on conda-forge yet maybe that is the issue?

**Comment by CagtayFabry** [comment]
so there  is an inconsistency between the conda dependencies and those in `setup.cfg` for version 0.3.1, does that matter?

**Comment by marscher** [comment]
The dependencies of conda packages are handled by the conda package manager and not setup.{py, cfg}. During the build step of a conda package the automatic dependency installation/handling of setup.py is being disabled. This allows the conda recipe to declare different things than setup.py

**Comment by CagtayFabry** [comment]
sounds good 🚀

**Review by CagtayFabry — APPROVED** [review]

**Comment by marscher** [comment]
Since this inconsistency will only prolong for one micro release, I guess we can live with that.

**Comment by CagtayFabry** [comment]
turns out this causes trouble when loading ASDF files due to additional version checking of the ASDF extension modules

with this environment
```
asdf=2.7.3
scipy=1.6.2
weldx=0.3.1 (from this update)
```
I get an error opening ASDF files
```
---------------------------------------------------------------------------
VersionConflict                           Traceback (most recent call last)
<ipython-input-6-32c8c1649cd5> in <module>
----> 1 with asdf.open(filename, custom_schema=file_schema) as asdf_file:
      2     weldx_file = asdf_file.tree

/srv/conda/envs/notebook/lib/python3.8/site-packages/asdf/asdf.py in open_asdf(fd, uri, mode, validate_checksums, extensions, do_not_fill_defaults, ignore_version_mismatch, ignore_unrecognized_tag, _force_raw_types, copy_arrays, lazy_load, custom_schema, strict_extension_check, ignore_missing_extensions, validate_on_read, _compat)
   1472         readonly = (mode == 'r' and not copy_arrays)
   1473 
-> 1474     instance = AsdfFile(extensions=extensions,
   1475                    ignore_version_mismatch=ignore_version_mismatch,
   1476                    ignore_unrecognized_tag=ignore_unrecognized_tag,

/srv/conda/envs/notebook/lib/python3.8/site-packages/asdf/asdf.py in __init__(self, tree, uri, extensions, version, ignore_version_mismatch, ignore_unrecognized_tag, ignore_implicit_conversion, copy_arrays, lazy_load, custom_schema, _readonly)
    113         self._extensions = []
    114         self._extension_metadata = {}
--> 115         self._process_extensions(extensions)
    116 
    117         if custom_schema is not None:

/srv/conda/envs/notebook/lib/python3.8/site-packages/asdf/asdf.py in _process_extensions(self, extensions)
    214     def _process_extensions(self, extensions):
    215         if extensions is None or extensions == []:
--> 216             self._extensions = default_extensions.extension_list
    217             self._extension_metadata = default_extensions.package_metadata
    218             return

/srv/conda/envs/notebook/lib/python3.8/site-packages/asdf/extension.py in extension_list(self)
    233     def extension_list(self):
    234         if self._extension_list is None:
--> 235             self._extension_list = AsdfExtensionList(self.extensions)
    236 
    237         return self._extension_list

/srv/conda/envs/notebook/lib/python3.8/site-packages/asdf/extension.py in extensions(self)
    226                 self._extensions.append(BuiltinExtension())
    227 
--> 228             self._load_installed_extensions()
    229 
    230         return self._extensions

/srv/conda/envs/notebook/lib/python3.8/site-packages/asdf/extension.py in _load_installed_extensions(self, group)
    196             with warnings.catch_warnings(record=True) as w:
    197                 warnings.simplefilter('always', category=AsdfDeprecationWarning)
--> 198                 ext = entry_point.load()
    199             if not issubclass(ext, AsdfExtension):
    200                 warnings.warn("Found entry point {}, from {} but it is not a "

/srv/conda/envs/notebook/lib/python3.8/site-packages/pkg_resources/__init__.py in load(self, require, *args, **kwargs)
   2469             )
   2470         if require:
-> 2471             self.require(*args, **kwargs)
   2472         return self.resolve()
   2473 

/srv/conda/envs/notebook/lib/python3.8/site-packages/pkg_resources/__init__.py in require(self, env, installer)
   2492         # requirements for that extra are purely optional and skip over them.
   2493         reqs = self.dist.requires(self.extras)
-> 2494         items = working_set.resolve(reqs, env, installer, extras=self.extras)
   2495         list(map(working_set.add, items))
   2496 

/srv/conda/envs/notebook/lib/python3.8/site-packages/pkg_resources/__init__.py in resolve(self, requirements, env, installer, replace_conflicting, extras)
    788                 # Oops, the "best" so far conflicts with a dependency
    789                 dependent_req = required_by[req]
--> 790                 raise VersionConflict(dist, req).with_context(dependent_req)
    791 
    792             # push the new requirements onto the stack

VersionConflict: (scipy 1.6.2 (/srv/conda/envs/notebook/lib/python3.8/site-packages), Requirement.parse('scipy<1.6'))
```

So we should avoid discrepancy between conda builds and source requirements
In the future probably just publish a fix release for the dependencies

can you revert this to be `<1.6` again for `0.3.1`with a new build number @marscher ?

**Pull request merged**
